apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-artemis.fullname" . }}
  labels:
    {{- include "simple-artemis.labels" . | nindent 4 }}
type: Opaque
data:
  simple-artemis.username: {{ .Values.artemisUsername | b64enc }}
  simple-artemis.password: {{ .Values.artemisPassword | b64enc }}

