apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-artemis.fullname" . }}
  labels:
    {{- include "simple-artemis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: 61616
      targetPort: all
      protocol: TCP
      name: all
    - port: 8161
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple-artemis.selectorLabels" . | nindent 4 }}
